# Generated by Django 3.2.4 on 2021-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossroads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='videos/crossroads/', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='videos/heroes/', max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='Warrior', max_length=100)),
            ],
        ),
    ]
