# Generated by Django 3.2.4 on 2021-08-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiance_choice', models.CharField(choices=[('LOH', 'LeaderOfHeroes'), ('DRM', 'Dream')], default='LOH', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoPathPreset', models.CharField(default='videos/S1/', max_length=60)),
                ('name', models.CharField(default='Scene Name', max_length=6)),
                ('requiredChoices', models.ManyToManyField(to='adventure.Choice')),
            ],
        ),
        migrations.DeleteModel(
            name='Crossroads',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='chunk',
            name='requiredVideos',
            field=models.ManyToManyField(to='adventure.Video'),
        ),
    ]
