# Generated by Django 3.2.4 on 2021-08-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20210821_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='audiance_choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceName',
            field=models.CharField(default='LOH', max_length=3),
        ),
        migrations.AlterField(
            model_name='video',
            name='requiredChoices',
            field=models.ManyToManyField(blank=True, to='adventure.Choice'),
        ),
    ]
