# Generated by Django 3.2.4 on 2021-08-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_remove_video_videopathpreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicePossibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='imgs/icons/', max_length=30)),
                ('optionName', models.CharField(default='CHOICE NAME', max_length=40)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.choice')),
            ],
        ),
    ]
