# Generated by Django 3.2.4 on 2021-08-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_choicepossibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicepossibility',
            old_name='path',
            new_name='imgPath',
        ),
    ]
