# Generated by Django 3.2.4 on 2021-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_rename_path_choicepossibility_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='nextChoice',
            field=models.ManyToManyField(to='adventure.Choice'),
        ),
    ]
