# Generated by Django 3.2.4 on 2021-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_chunk_nextchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='binaryChoice',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='chunkNum',
            field=models.IntegerField(default=1),
        ),
    ]
